version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: inflearn-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: inflearn
      POSTGRES_PASSWORD: inflearn1234
      POSTGRES_DB: inflearn
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
